name: 🐞 Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: [Bug, Needs Triage]
body:
- type: checkboxes
  value: true
  attributes:
    label: 已完整填写表单
    id: all-filled-checkboxes
    options:
    - label: 我确认
      required: true
- type: checkboxes
  value: true
  attributes:
    label: 已设置合适的标题
    id: title-filled-checkboxes
    options:
    - label: 我确认
      required: true
