name: 🐞 Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: [Bug, Needs Triage]
body:
- type: input
  id: contact
  attributes:
    label: 角色名称
    placeholder: 旅行者
  validations:
    required: true
- type: checkboxes
  id: all-filled-checkboxes
  attributes:
    label: 已完整填写表单
    options:
    - label: 我确认
      required: true
- type: checkboxes
  id: title-filled-checkboxes
  attributes:
    label: 已设置合适的标题
    options:
    - label: 我确认
      required: true
