name: Artifact Rating Rules
description: 圣遗物评分细则建议
title: "[Artifact Rating] 请在这里填写角色名称"
labels: area-AvatarInfo
assignees: Lightczx
body:
- type: markdown
  attributes:
    value: "请按下方的要求填写完整的问题表单"
- type: input
  id: contact1
  attributes:
    label: 角色名称
    placeholder: 旅行者
  validations:
    required: true
- type: input
  id: contact2
  attributes:
    label: 生命值
    placeholder: "10"
  validations:
    required: true
- type: input
  id: contact3
  attributes:
    label: 攻击力
    placeholder: "10"
  validations:
    required: true
- type: input
  id: contact4
  attributes:
    label: 防御力
    placeholder: "10"
  validations:
    required: true
- type: input
  id: contact5
  attributes:
    label: 暴击率
    placeholder: "10"
  validations:
    required: true
- type: input
  id: contact6
  attributes:
    label: 暴击伤害
    placeholder: "10"
  validations:
    required: true
- type: input
  id: contact7
  attributes:
    label: 元素精通
    placeholder: "10"
  validations:
    required: true
- type: input
  id: contact8
  attributes:
    label: 充能效率
    placeholder: "10"
  validations:
    required: true
- type: input
  id: contact9
  attributes:
    label: 治疗加成
    placeholder: "10"
  validations:
    required: true
- type: input
  id: contact10
  attributes:
    label: 元素伤害
    placeholder: "10"
  validations:
    required: true
- type: textarea
  attributes:
    label: 补充
  validations:
    required: false
- type: checkboxes
  id: all-filled-checkboxes
  attributes:
    label: 已完整填写表单
    options:
    - label: 我确认
      required: true
- type: checkboxes
  id: title-filled-checkboxes
  attributes:
    label: 已设置合适的标题
    options:
    - label: 我确认
      required: true
